apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudability-metrics-agent.fullname" . }}
  labels:
    {{- include "cloudability-metrics-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudability-metrics-agent.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ include "cloudability-metrics-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
