apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudability-metrics-agent.fullname" . }}
  labels:
    {{- include "cloudability-metrics-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: cloudability
  namespace: cloudability
roleRef:
  kind: Role
  name: {{ include "cloudability-metrics-agent.fullname" . }};
  apiGroup: rbac.authorization.k8s.io
